# -*- coding: utf-8 -*-
"""4_etl_queries.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ6gmeon4i9wsNw9yi07zjS8zaTIEKvc
"""

-- Project 4: ETL warehouse (tables: fact_orders, dim_customers, dim_products)

-- Row-count reconciliation after load
SELECT 'fact_orders' AS tbl, COUNT(*) AS n FROM fact_orders
UNION ALL SELECT 'dim_customers', COUNT(*) FROM dim_customers
UNION ALL SELECT 'dim_products', COUNT(*) FROM dim_products;

-- Data-quality check: orphan keys (should return 0)
SELECT COUNT(*) AS orphan_orders FROM fact_orders f
LEFT JOIN dim_customers c ON f.customer_id = c.customer_id WHERE c.customer_id IS NULL;

-- Revenue and profit by category and segment (joins)
SELECT p.category, c.segment, ROUND(SUM(f.sales),0) AS revenue, ROUND(SUM(f.profit),0) AS profit
FROM fact_orders f
JOIN dim_products p ON f.product_id = p.product_id
JOIN dim_customers c ON f.customer_id = c.customer_id
GROUP BY p.category, c.segment ORDER BY revenue DESC;

-- Top 10 customers by revenue
SELECT c.customer_name, ROUND(SUM(f.sales),0) AS revenue
FROM fact_orders f JOIN dim_customers c ON f.customer_id = c.customer_id
GROUP BY c.customer_name ORDER BY revenue DESC LIMIT 10;

-- Customers above average spend (subquery)
SELECT customer_id, ROUND(total,0) AS total FROM
 (SELECT customer_id, SUM(sales) AS total FROM fact_orders GROUP BY customer_id) t
WHERE total > (SELECT AVG(total) FROM (SELECT SUM(sales) AS total FROM fact_orders GROUP BY customer_id) a);