# -*- coding: utf-8 -*-
"""4_etl_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuCsJ8w5ZV3efR3wgg0YS8CupT8blbHu
"""

"""Project 4: ETL Pipeline - Python + MySQL (source: Superstore Sales CSV)
Usage:  MySQL ->  set DB_URL=mysql+pymysql://user:password@localhost:3306/portfolio  (pip install pymysql)
        default -> SQLite file etl_demo.db (so it runs anywhere)"""
import os
import logging
import pandas as pd
from sqlalchemy import create_engine

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
SRC = "data/Sample - Superstore.csv"
DB_URL = os.getenv("DB_URL", "sqlite:///etl_demo.db")


def extract(path):
    df = pd.read_csv(path, encoding="latin-1")
    logging.info("Extracted %d rows", len(df))
    return df


def validate(df):
    """Basic data-quality checks: duplicates, nulls, data types."""
    report = {
        "duplicate_rows": int(df.duplicated().sum()),
        "null_cells": int(df.isna().sum().sum()),
        "sales_is_numeric": pd.api.types.is_numeric_dtype(df["sales"]),
    }
    logging.info("Validation report: %s", report)
    assert report["sales_is_numeric"], "Sales column must be numeric"
    return report


def transform(df):
    df = df.drop_duplicates().copy()
    df.columns = [c.strip().lower().replace(" ", "_").replace("-", "_") for c in df.columns]
    df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)
    df["ship_date"] = pd.to_datetime(df["ship_date"], dayfirst=True)
    df["order_year"] = df["order_date"].dt.year
    df["profit_margin"] = (df["profit"] / df["sales"]).round(4)
    logging.info("Transformed to %d rows", len(df))
    return df


def load(df, url):
    engine = create_engine(url)
    # Relational split: customers, products, orders (fact table)
    customers = df[["customer_id", "customer_name", "segment", "region", "state", "city"]].drop_duplicates("customer_id")
    products = df[["product_id", "product_name", "category", "sub_category"]].drop_duplicates("product_id")
    orders = df[["row_id", "order_id", "order_date", "ship_date", "ship_mode", "customer_id",
                 "product_id", "sales", "quantity", "discount", "profit", "profit_margin", "order_year"]]
    customers.to_sql("dim_customers", engine, if_exists="replace", index=False)
    products.to_sql("dim_products", engine, if_exists="replace", index=False)
    orders.to_sql("fact_orders", engine, if_exists="replace", index=False)
    logging.info("Loaded dim_customers=%d dim_products=%d fact_orders=%d", len(customers), len(products), len(orders))


if __name__ == "__main__":
    raw = extract(SRC)
    validate(raw)
    clean = transform(raw)
    load(clean, DB_URL)
    logging.info("ETL complete")